source $HOME/.dotfiles/vim/settings/plugins.vim
source $HOME/.dotfiles/vim/settings/keybindings.vim
source $HOME/.dotfiles/vim/settings/gen_settings.vim
source $HOME/.dotfiles/vim/settings/colorschemes.vim
source $HOME/.dotfiles/vim/settings/gvim_settings.vim
