" KEYBINDINGS
let mapleader = ";"
nmap <silent> <leader>wq :wq<CR>
nmap <silent> <leader>w :w<CR>
nmap <silent> <leader>W :wa<CR>
nmap <silent> <leader>q :q<CR>
nmap <silent> <leader>Q :qa<CR>
nmap <silent> <leader>h :sp<CR>
nmap <silent> <leader>v :vsp<CR>
nmap <TAB> <C-w>
inoremap jj <ESC>

" SETTINGS
syntax on
set number
set backspace=indent,eol,start
set showcmd
set mouse=a
set encoding=UTF-8
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
set background=light
highlight LineNr ctermfg=grey

execute pathogen#infect('~/.vim/gvim/{}')

" ----- MacVim Screen Config
" set guifont=Iosevka:h16
" set guifont=Inconsolata:h16
" colorscheme panda

" ----- Start MacVim in fullscreen
" set fuoptions=maxvert,maxhorz
" au GUIEnter * set fullscreen

" autocmd VimEnter * PlugInstall
" autocmd VimEnter * q

set guioptions-=T
set guioptions-=m
set guioptions-=r
set guioptions-=b
