" KEYBINDINGS
let mapleader = ";"
nmap <silent> <leader>wq :wq<CR>
nmap <silent> <leader>w :w<CR>
nmap <silent> <leader>W :wa<CR>
nmap <silent> <leader>q :q<CR>
nmap <silent> <leader>Q :qa<CR>
nmap <silent> <leader>h :sp<CR>
nmap <silent> <leader>v :vsp<CR>
nmap <TAB> <C-w>
inoremap jj <ESC>

" SETTINGS
syntax on
set number
set backspace=indent,eol,start
set showcmd
set mouse=a
set encoding=UTF-8
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
set background=light
" highlight LineNr ctermfg=grey

filetype plugin indent on
call plug#begin('~/.vim/gvim')
Plug 'Raimondi/delimitMate'
Plug 'Shougo/deoplete.nvim'
Plug 'Shougo/deoplete-clangx'
Plug 'junegunn/fzf.vim'
Plug 'junegunn/gv.vim'
Plug 'junegunn/goyo.vim'
Plug 'roxma/nvim-yarp'
Plug 'vim-airline/vim-airline'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-dispatch'
Plug 'tpope/vim-eunuch'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-unimpaired'
Plug 'tpope/vim-vinegar'
Plug 'roxma/vim-hug-neovim-rpc'
Plug 'vivien/vim-linux-coding-style'
Plug 'vimwiki/vimwiki'
call plug#end()

" ----- MacVim Screen Config
" set guifont=Iosevka:h16
" set guifont=Inconsolata:h16
" colorscheme panda

" ----- Start MacVim in fullscreen
" set fuoptions=maxvert,maxhorz
" au GUIEnter * set fullscreen

" autocmd VimEnter * PlugInstall
" autocmd VimEnter * q

set guioptions-=T
set guioptions-=m
set guioptions-=r
set guioptions-=b
