" KEYBINDINGS
let mapleader = ";"
nmap <silent> <leader>wq :wq<CR>
nmap <silent> <leader>w :w<CR>
nmap <silent> <leader>W :wa<CR>
nmap <silent> <leader>q :q<CR>
nmap <silent> <leader>Q :qa<CR>
nmap <silent> <leader>h :sp<CR>
nmap <silent> <leader>v :vsp<CR>
nmap <TAB> <C-w>
inoremap jj <ESC>

" SETTINGS
" Important Settings
syntax on
set autoindent
set backspace=indent,eol,start
highlight LineNr ctermfg=grey

"  PATHOGEN SETUP
filetype plugin indent on
execute pathogen#infect('~/.vim/plugs/{}')
